version: '2.2'
networks:
  nginx-proxy:
    external: true
services:
  node:
    build:
      context: .docker
      dockerfile: node/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}poc-datagrid/node'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/app'
      - 'node-cache:/home/node/.cache'
      - 'node-npm-packages:/home/node/.npm-packages'
    environment:
      - VIRTUAL_HOST=${DOCKER_DEVBOX_DOMAIN_PREFIX}.${DOCKER_DEVBOX_DOMAIN}
    networks:
      - default
      - nginx-proxy
volumes:
  node-cache: null
  node-npm-packages: null
